/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.io.IOException;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ASUS
 */
public class ConsultaGeneral extends javax.swing.JFrame {

    ArrayList<Libro> libros = Libro.cargarLibros();
    
    /**
     * Creates new form ConsultaGeneral
     */
    public ConsultaGeneral() {
        initComponents();
        setLocationRelativeTo(null);

        for (Libro libro : libros) {
            String autor = libro.obtenerAutor();
            String genero = libro.obtenerGenero();

            boolean existe = false;

            for (int i = 0; i < CBXAutores.getItemCount(); i++) {

                if (CBXAutores.getItemAt(i).equals(autor)) {
                    existe = true;
                    break;
                }
                existe = false;
            }

            if (!existe) {
                CBXAutores.addItem(autor);
            }

            existe = false;
            for (int i = 0; i < CBXGenero.getItemCount(); i++) {

                if (CBXGenero.getItemAt(i).equals(genero)) {
                    existe = true;
                    break;
                }
                existe = false;
            }
            if (!existe) {
                CBXGenero.addItem(genero);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        consultaTxt = new javax.swing.JTextField();
        consultaBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultaTabla = new javax.swing.JTable();
        consultaTipo = new javax.swing.JComboBox<>();
        consultaLimpiar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GeneralConsultaTabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CBXAutores = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        MostrarAutor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TLibrosAutor = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CBXGenero = new javax.swing.JComboBox<>();
        MostrarGenero = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TLibrosGenero = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        consultaBuscar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Consulta por Código");

        consultaTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        consultaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaTxtActionPerformed(evt);
            }
        });

        consultaBuscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        consultaBuscar.setText("Buscar");
        consultaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaBuscarActionPerformed(evt);
            }
        });

        consultaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Autor", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(consultaTabla);

        consultaTipo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        consultaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Título", "Autor", "Código" }));
        consultaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaTipoActionPerformed(evt);
            }
        });

        consultaLimpiar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        consultaLimpiar.setText("Limpiar tabla");
        consultaLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consultaBuscar)
                            .addComponent(consultaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultaLimpiar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consultaTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaBuscar)
                    .addComponent(consultaLimpiar))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Busqueda", jPanel1);

        GeneralConsultaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Autor", "Género", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(GeneralConsultaTabla);

        jButton1.setText("CONSULTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Libros");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel4)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONSULTA GENERAL", jPanel5);

        CBXAutores.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CBXAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBXAutoresActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Libros por Autor");

        MostrarAutor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MostrarAutor.setText("Mostrar");
        MostrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarAutorActionPerformed(evt);
            }
        });

        TLibrosAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Autor", "Género", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TLibrosAutor);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("ESTADÍSTICA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(CBXAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MostrarAutor))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBXAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarAutor))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Libros por Autor", jPanel2);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Libros por Género");

        CBXGenero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CBXGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBXGeneroActionPerformed(evt);
            }
        });

        MostrarGenero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MostrarGenero.setText("Mostrar");
        MostrarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarGeneroActionPerformed(evt);
            }
        });

        TLibrosGenero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Autor", "Género", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TLibrosGenero);

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("ESTADÍSTICA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(CBXGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MostrarGenero))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton3)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBXGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarGenero))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Libros por Genero", jPanel3);

        consultaBuscar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        consultaBuscar1.setText("LOGIN");
        consultaBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(consultaBuscar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(consultaBuscar1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //listener vacio
    private void consultaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaTxtActionPerformed

    private void consultaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBuscarActionPerformed
        // TODO add your handling code here:
        String consulta = consultaTxt.getText();
        int index = consultaTipo.getSelectedIndex();
        Libro miLibro = new Libro();
        try {
            switch (index) {
                case 0:
                    miLibro = busqueda(consulta, index);
                    break;
                case 1:
                    miLibro = busqueda(consulta, index);
                    break;
                case 2:
                    miLibro = busqueda(consulta, index);
                    break;
            }

            // XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            DefaultTableModel model = (DefaultTableModel) consultaTabla.getModel();

            String[] elementos = miLibro.obtenerDatos();
            model.insertRow(model.getRowCount(), new Object[]{elementos[0], elementos[1], elementos[2], elementos[3], elementos[4]});

            // XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo encontrar el libro");
        }

    }//GEN-LAST:event_consultaBuscarActionPerformed

    private Libro busqueda(String porBuscar, int tipo) throws IOException {
        Libro miLibro = null;
        switch (tipo) {
            case 0:
                for (Libro libroTemp : libros) {
                    if (porBuscar.equals(libroTemp.obtenerTitulo())) {
                        miLibro = libroTemp;
                    }
                }
                break;
            case 1:
                for (Libro libroTemp : libros) {
                    if (porBuscar.equals(libroTemp.obtenerAutor())) {
                        miLibro = libroTemp;
                    }
                }
                break;
            case 2:
                for (Libro libroTemp : libros) {
                    if (porBuscar.equals(libroTemp.obtenerCodigo())) {
                        miLibro = libroTemp;
                    }
                }
                break;
        }
        return miLibro;
    }

    //listener vacio
    private void consultaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaTipoActionPerformed

    //limpia la tabla
    private void consultaLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaLimpiarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) consultaTabla.getModel();

        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_consultaLimpiarActionPerformed

    ///llama al al siguiente jframe, se debe borrar los parametros cuando este listo los archivos.dat
    private void consultaBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBuscar1ActionPerformed
        this.setVisible(false);
        Login lg = new Login();
        lg.setSize(780, 670);
        lg.setVisible(true);
    }//GEN-LAST:event_consultaBuscar1ActionPerformed

    private void MostrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarAutorActionPerformed

        DefaultTableModel model = (DefaultTableModel) TLibrosAutor.getModel();
        model.setRowCount(0);
        for (Libro libro : libros) {
            if (libro.obtenerAutor().equals(CBXAutores.getSelectedItem())) {
                String[] datos = libro.obtenerDatos();
                model.insertRow(model.getRowCount(), new Object[]{datos[0], datos[1], datos[2], datos[3],datos[4]});
            }
        }
    }//GEN-LAST:event_MostrarAutorActionPerformed

    private void MostrarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarGeneroActionPerformed

        DefaultTableModel model = (DefaultTableModel) TLibrosGenero.getModel();
        model.setRowCount(0);
        for (Libro libro : libros) {
            if (libro.obtenerGenero().equals(CBXGenero.getSelectedItem())) {
                String[] datos = libro.obtenerDatos();
                model.insertRow(model.getRowCount(), new Object[]{datos[0], datos[1], datos[2], datos[3], datos[4]});
            }
        }
    }//GEN-LAST:event_MostrarGeneroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) GeneralConsultaTabla.getModel();
        model.setRowCount(0);
        for (Libro libro : libros) {
            String[] datos = libro.obtenerDatos();
            model.insertRow(model.getRowCount(), new Object[]{datos[0], datos[1], datos[2], datos[3], datos[4]});
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CBXGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBXGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBXGeneroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            int cont = 0;
            int cont2 = 0;
            int [] cantLibros = new int [CBXAutores.getItemCount()];
            for(int i = 0; i<CBXAutores.getItemCount(); i++){
                for(Libro libro : libros){
                     if(libro.obtenerAutor().equals(CBXAutores.getItemAt(i))){
                        cont++;
                    } 
                }
                cantLibros[i] = cont;
                cont = 0;
            }
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            for(int i = 0; i<CBXAutores.getItemCount();i++){
                 dataset.setValue(cantLibros[i],"CANTIDAD LIBROS", CBXAutores.getItemAt(i));
            }
           JFreeChart chart = ChartFactory.createBarChart("LIBROS POR AUTOR","AUTOR","CANTIDAD LIBROS",dataset);
           CategoryPlot p = chart.getCategoryPlot();
          // p.setRangeGridlinePaint(Color.black);
           ChartFrame frame = new ChartFrame("DIAGRAMA DE BARRAS",chart);
           frame.setVisible(true);
           frame.setLocationRelativeTo(null);
           frame.setSize(800,800);
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CBXAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBXAutoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBXAutoresActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            int cont = 0;
            int cont2 = 0;
            int [] cantLibros = new int [CBXGenero.getItemCount()];
            for(int i = 0; i<CBXGenero.getItemCount(); i++){
                for(Libro libro : libros){
                     if(libro.obtenerGenero().equals(CBXGenero.getItemAt(i))){
                        cont++;
                    } 
                }
                cantLibros[i] = cont;
                cont = 0;
            }
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            for(int i = 0; i<CBXGenero.getItemCount();i++){
                 dataset.setValue(cantLibros[i],"CANTIDAD LIBROS", CBXGenero.getItemAt(i));
            }
           JFreeChart chart = ChartFactory.createBarChart("LIBROS POR GENERO","GENERO","CANTIDAD LIBROS",dataset);
           CategoryPlot p = chart.getCategoryPlot();
          // p.setRangeGridlinePaint(Color.black);
           ChartFrame frame = new ChartFrame("DIAGRAMA DE BARRAS",chart);
           frame.setVisible(true);
           frame.setLocationRelativeTo(null);
           frame.setSize(800,800);
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaGeneral.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaGeneral.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaGeneral.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaGeneral.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBXAutores;
    private javax.swing.JComboBox<String> CBXGenero;
    private javax.swing.JTable GeneralConsultaTabla;
    private javax.swing.JButton MostrarAutor;
    private javax.swing.JButton MostrarGenero;
    private javax.swing.JTable TLibrosAutor;
    private javax.swing.JTable TLibrosGenero;
    private javax.swing.JButton consultaBuscar;
    private javax.swing.JButton consultaBuscar1;
    private javax.swing.JButton consultaLimpiar;
    private javax.swing.JTable consultaTabla;
    private javax.swing.JComboBox<String> consultaTipo;
    private javax.swing.JTextField consultaTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
